### ISSUE TITLE
missing template `dhcpd.conf.j2`

### ISSUE THREAD

**Issue by flybyray** [adfinis-sygroup/ansible-role-isc_dhcp_server#4]
https://github.com/adfinis-sygroup/ansible-role-isc_dhcp_server/blob/d664e73d421d34214f46b0a739887986fd1164d1/tasks/configuration.yml#L5

**Comment by karras** [comment]
Thanks a lot for the issue! I've just added the missing template in PR #5. Note sure how I could have missed that in the initial PR. Sorry about that!

Let's blame the reviewer instead. ;)

**Comment by karras** [comment]
Also please feel free to open a PR or feature request if you miss any config options in the template.
